### ISSUE TITLE
Memory Error Exceptions

### ISSUE THREAD

**Issue by grimpunch** [grimpunch/TLDRifyBot#7]
2015-04-07 17:14:23,508 ERROR ('Exception:', MemoryError())
Traceback (most recent call last):
  File "**init**.py", line 294, in <module>
    task()
  File "**init**.py", line 257, in check_for_requests
    comments_already_done.add(cid)
MemoryError

Discovered while about to work on another issue, need to investigate the memory usage of the application and reduce memory build up

**Comment by grimpunch** [comment]
Fixed in 3ec9a5c4ce821792425c22414dd85c60fb067b5c
